<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GA1O7MP" failures="0" tests="5" name="failedXML_Study.Failed_XML1" time="0.153" errors="1" timestamp="2022-04-06T16:25:08 IST" skipped="0">
  <testcase classname="failedXML_Study.Failed_XML1" name="Method5" time="0.003"/>
  <system-out>
    <![CDATA[Method 5 is running]]>
  </system-out>
  <testcase classname="failedXML_Study.Failed_XML1" name="Method1" time="0.134">
    <error message="Method failedXML_Study.Failed_XML1.Method1() didn&#039;t finish within the time-out 100" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method failedXML_Study.Failed_XML1.Method1() didn't finish within the time-out 100
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Method1 -->
  <system-out/>
  <testcase classname="failedXML_Study.Failed_XML1" name="Method2" time="0.007"/>
  <system-out>
    <![CDATA[Method 2 is running]]>
  </system-out>
  <testcase classname="failedXML_Study.Failed_XML1" name="Method4" time="0.004"/>
  <system-out>
    <![CDATA[Method 4 is running]]>
  </system-out>
  <testcase classname="failedXML_Study.Failed_XML1" name="Method3" time="0.005"/>
  <system-out>
    <![CDATA[Method 3 is running]]>
  </system-out>
</testsuite> <!-- failedXML_Study.Failed_XML1 -->
